### ISSUE TITLE
Restart() method missing?

### ISSUE THREAD

**Issue by dkotik** [leaanthony/spinner#1]
Using v0.5.3 - method "Restart" is missing?

**Comment by leaanthony** [comment]
Hi @dkotik. Restart() was removed at the v0.3 release. There was an interesting race condition when using it and as I didn't have time to look at it, I removed it. If you want it back, and have time to debug that (use v0.2) then I'd be more than happy to review a PR 👍

**Comment by dkotik** [comment]
Ok! Thank you for clarification - I just was confused by this paragraph in Readme: <https://github.com/leaanthony/spinner#resuse-spinner> It needs, perhaps be removed, for now? I am ok without a Restart method.

**Comment by leaanthony** [comment]
Good catch! I will update it 👍👍👍

**Comment by leaanthony** [comment]
At some point, I'll revisit this. Thanks for raising it!
